// <auto-generated />
namespace WebApiCapacitacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CARGAS_FAMILIARES : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CARGAS_FAMILIARES));
        
        string IMigrationMetadata.Id
        {
            get { return "202003261642285_CARGAS_FAMILIARES"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
